Debug on jetson
hydronautics-team/sauvc pull request #3
Opened 2022-09-03 17:44 UTC by vladushked

2022-09-05 15:48 UTC, Davt2000 requested changes
Оставил одно предложение насчет оптимизации
И есть повторяющаяся опечатка, которая ломает лаунчи

2022-09-05 15:48 UTC, Davt2000 commented on build.sh
> +catkin_make -DCATKIN_BLACKLIST_PACKAGES="stingray_gazebo_communication"
Т е пока газебо бридж остаётся, но не используется?

2022-09-05 15:48 UTC, Davt2000 commented on src/sauvc_startup/launch/main.launch
> +
Можешь сюда или в стингреевский лаунч добавить возможность отключить дебаг вывод от нейронки и окна с выводом камеры без нейронки?

2022-09-05 15:48 UTC, Davt2000 commented on src/sauvc_startup/launch/sauvc_qr_demo.launch
> +        <param name="front_camera" value="$(arg front_cam)" />
ты забыл поменять value="$(arg front_cam)" на value="$(arg front_camera)"

2022-09-05 15:48 UTC, Davt2000 commented on src/sauvc_startup/launch/sauvc_qr_drums.launch
> +        <param name="front_camera" value="$(arg front_cam)" />
аналогично предыдущему front_cam не переименовано

2022-09-05 15:48 UTC, Davt2000 commented on src/sauvc_startup/launch/sauvc_qr_medium.launch
> +        <param name="front_camera" value="$(arg front_cam)" />
аналогично

2022-09-05 15:48 UTC, Davt2000 commented on src/sauvc_startup/launch/sauvc_qr_medium_ha.launch
> +        <param name="front_camera" value="$(arg front_cam)" />
и тут тоже

2022-09-05 15:48 UTC, Davt2000 commented on src/sauvc_startup/launch/sauvc_qr_simple.launch
> +        <param name="front_camera" value="$(arg front_cam)" />
...

2022-09-05 15:48 UTC, Davt2000 commented on src/sauvc_startup/launch/sauvc_qr_test_vma.launch
> +        <param name="front_camera" value="/front_camera/image_raw" />
можно кста как вариант сделать TestMission независимым от контроллера, и прописать ему прямо в файле запуск ноды
типа как
```
if __name__ == '__main__':
    rospy.init_node("test_mission")
    front_camera_topic = rospy.get_param('~front_camera_topic')
    bottom_camera_topic = rospy.get_param('~front_camera_topic')
    test_mission = TestMission(...)
    test_mission.run()
```

2022-09-06 10:08 UTC, vladushked commented on build.sh
> +catkin_make -DCATKIN_BLACKLIST_PACKAGES="stingray_gazebo_communication"
это билд скрипт для джетсона
там газебо нет и поэтому я исключаю пакет чтобы не ломалось

2022-09-06 10:11 UTC, vladushked commented on src/sauvc_startup/launch/main.launch
> +
а там есть этот аргумент

2022-09-06 10:11 UTC, vladushked commented on src/sauvc_startup/launch/main.launch
> +
> Можешь сюда или в стингреевский лаунч добавить возможность отключить дебаг вывод от нейронки и окна с выводом камеры без нейронки?

а там есть этот аргумент

2022-09-06 10:14 UTC, vladushked commented on src/sauvc_startup/launch/main.launch
> +
> Можешь сюда или в стингреевский лаунч добавить возможность отключить дебаг вывод от нейронки и окна с выводом камеры без нейронки?

окна с выводом камер тоже по дефолту отрублены, аргумент SHOW
надо будет при запуске наоборот прописывать DEBUG:=TRUE SHOW:=TRUE

2022-09-06 10:14 UTC, vladushked commented on build.sh
> +catkin_make -DCATKIN_BLACKLIST_PACKAGES="stingray_gazebo_communication"
> Т е пока газебо бридж остаётся, но не используется?

я его назову build_jetson

2022-09-07 17:28 UTC, merged